import { z } from "zod"

import {
  PlanningDraftAgentBriefSchema,
  runIpAllocationPlannerInChildSession,
} from "../../agents"
import type { WorkerInput, WorkerResult, WorkerRuntimeContext } from "../../coordinator/types"
import { finalizePlanningDraftStructuredInput } from "../planning-draft-shared"

const PlanningDraftWorkerContextSchema = z.object({
  plannerBrief: PlanningDraftAgentBriefSchema,
})

export async function executeIpAllocationPlannerWorker(
  input: WorkerInput,
  runtime: WorkerRuntimeContext,
): Promise<WorkerResult> {
  const parsedContext = PlanningDraftWorkerContextSchema.safeParse(input.context ?? {})
  if (!parsedContext.success) {
    return {
      workerId: "ip-allocation-planner",
      status: "failed",
      output: {},
      recommendations: [],
      errors: ["IP allocation planner worker requires context.plannerBrief."],
    }
  }

  const result = await runIpAllocationPlannerInChildSession({
    brief: parsedContext.data.plannerBrief,
    runtime,
  })
  if (!result.success) {
    return result.result
  }

  return {
    workerId: "ip-allocation-planner",
    status: result.result.status,
    output: {
      structuredInput: finalizePlanningDraftStructuredInput({
        structuredInput: result.result.output.structuredInput,
        plannerRef: "planner:ip-allocation",
        plannerNote: "Advisory draft generated by the IP allocation planner.",
      }),
      planningWarnings: result.result.output.planningWarnings,
    },
    recommendations: ["draft_topology_model"],
    ...(result.result.errors && result.result.errors.length > 0
      ? {
          errors: result.result.errors,
        }
      : {}),
  }
}

export default executeIpAllocationPlannerWorker
