import type { CloudSolutionSliceInput } from "../domain"

export function createScn01SingleRackConnectivityFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-01",
      projectName: "SCN-01 Single Rack Basic Connectivity",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-plan",
        "device-port-connection-table",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-switch-a",
        name: "switch-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-server-a",
        name: "server-a",
        role: "server",
        rackId: "rack-a",
        rackPosition: 10,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-server-b",
        name: "server-b",
        role: "server",
        rackId: "rack-a",
        rackPosition: 14,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-switch-a-1",
        deviceId: "device-switch-a",
        name: "eth0",
        purpose: "server-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-switch-a-2",
        deviceId: "device-switch-a",
        name: "eth1",
        purpose: "server-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-server-a-1",
        deviceId: "device-server-a",
        name: "eth0",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-server-b-1",
        deviceId: "device-server-b",
        name: "eth0",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-server-a",
        endpointA: { portId: "port-switch-a-1" },
        endpointB: { portId: "port-server-a-1" },
        purpose: "server-a-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-server-b",
        endpointA: { portId: "port-switch-a-2" },
        endpointB: { portId: "port-server-b-1" },
        purpose: "server-b-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-management",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.10.0.0/24",
        gateway: "10.10.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-gateway",
        segmentId: "segment-management",
        allocationType: "gateway",
        ipAddress: "10.10.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-server-a",
        segmentId: "segment-management",
        allocationType: "device",
        ipAddress: "10.10.0.10",
        deviceId: "device-server-a",
        interfaceName: "eth0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-server-b",
        segmentId: "segment-management",
        allocationType: "device",
        ipAddress: "10.10.0.11",
        deviceId: "device-server-b",
        interfaceName: "eth0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn02DualTorFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-02",
      projectName: "SCN-02 Dual ToR Redundant Rack",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-plan",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-tor-a",
        name: "tor-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-tor-b",
        name: "tor-b",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 2,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-storage-a",
        name: "storage-a",
        role: "storage",
        redundancyIntent: "dual-homed-required",
        rackId: "rack-a",
        rackPosition: 10,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-a",
        name: "compute-a",
        role: "server",
        redundancyIntent: "dual-homed-required",
        rackId: "rack-a",
        rackPosition: 14,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-tor-a-1",
        deviceId: "device-tor-a",
        name: "eth0",
        purpose: "uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-b-1",
        deviceId: "device-tor-b",
        name: "eth0",
        purpose: "uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-a-2",
        deviceId: "device-tor-a",
        name: "eth1",
        purpose: "uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-b-2",
        deviceId: "device-tor-b",
        name: "eth1",
        purpose: "uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-storage-a-1",
        deviceId: "device-storage-a",
        name: "eth0",
        purpose: "storage-a-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-storage-a-2",
        deviceId: "device-storage-a",
        name: "eth1",
        purpose: "storage-a-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-1",
        deviceId: "device-compute-a",
        name: "eth0",
        purpose: "compute-a-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-2",
        deviceId: "device-compute-a",
        name: "eth1",
        purpose: "compute-a-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-storage-a-primary",
        endpointA: { portId: "port-tor-a-1" },
        endpointB: { portId: "port-storage-a-1" },
        purpose: "storage-primary",
        redundancyGroup: "storage-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-storage-a-secondary",
        endpointA: { portId: "port-tor-b-1" },
        endpointB: { portId: "port-storage-a-2" },
        purpose: "storage-secondary",
        redundancyGroup: "storage-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a-primary",
        endpointA: { portId: "port-tor-a-2" },
        endpointB: { portId: "port-compute-a-1" },
        purpose: "compute-primary",
        redundancyGroup: "compute-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a-secondary",
        endpointA: { portId: "port-tor-b-2" },
        endpointB: { portId: "port-compute-a-2" },
        purpose: "compute-secondary",
        redundancyGroup: "compute-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-mgmt",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.20.0.0/24",
        gateway: "10.20.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "segment-storage",
        name: "storage",
        segmentType: "storage",
        cidr: "172.16.0.0/24",
        gateway: "172.16.0.1",
        purpose: "storage",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-mgmt-gateway",
        segmentId: "segment-mgmt",
        allocationType: "gateway",
        ipAddress: "10.20.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-gateway",
        segmentId: "segment-storage",
        allocationType: "gateway",
        ipAddress: "172.16.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.20.0.10",
        deviceId: "device-storage-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-a-service",
        segmentId: "segment-storage",
        allocationType: "device",
        ipAddress: "172.16.0.10",
        deviceId: "device-storage-a",
        interfaceName: "eth0/eth1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.20.0.11",
        deviceId: "device-compute-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-a-service",
        segmentId: "segment-storage",
        allocationType: "device",
        ipAddress: "172.16.0.11",
        deviceId: "device-compute-a",
        interfaceName: "eth0/eth1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn03MultiRackPodFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-03",
      projectName: "SCN-03 Small Multi-Rack Pod",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-connection-table",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "rack-b",
        name: "rack-b",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-leaf-a",
        name: "leaf-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-leaf-b",
        name: "leaf-b",
        role: "switch",
        rackId: "rack-b",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-a",
        name: "compute-a",
        role: "server",
        rackId: "rack-a",
        rackPosition: 12,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-b",
        name: "compute-b",
        role: "server",
        rackId: "rack-b",
        rackPosition: 12,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-leaf-a-1",
        deviceId: "device-leaf-a",
        name: "eth0",
        purpose: "inter-rack",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-b-1",
        deviceId: "device-leaf-b",
        name: "eth0",
        purpose: "inter-rack",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-a-2",
        deviceId: "device-leaf-a",
        name: "eth1",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-b-2",
        deviceId: "device-leaf-b",
        name: "eth1",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-1",
        deviceId: "device-compute-a",
        name: "eth0",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-b-1",
        deviceId: "device-compute-b",
        name: "eth0",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-inter-rack",
        endpointA: { portId: "port-leaf-a-1" },
        endpointB: { portId: "port-leaf-b-1" },
        purpose: "inter-rack-fabric",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a",
        endpointA: { portId: "port-leaf-a-2" },
        endpointB: { portId: "port-compute-a-1" },
        purpose: "compute-access",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-b",
        endpointA: { portId: "port-leaf-b-2" },
        endpointB: { portId: "port-compute-b-1" },
        purpose: "compute-access",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-mgmt",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.30.0.0/24",
        gateway: "10.30.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "segment-service",
        name: "service",
        segmentType: "service",
        cidr: "10.31.0.0/24",
        gateway: "10.31.0.1",
        purpose: "service",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-compute-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.30.0.10",
        deviceId: "device-compute-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-b-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.30.0.11",
        deviceId: "device-compute-b",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-leaf-a-service",
        segmentId: "segment-service",
        allocationType: "device",
        ipAddress: "10.31.0.10",
        deviceId: "device-leaf-a",
        interfaceName: "loopback0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-leaf-b-service",
        segmentId: "segment-service",
        allocationType: "device",
        ipAddress: "10.31.0.11",
        deviceId: "device-leaf-b",
        interfaceName: "loopback0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn04CloudNetworkAllocationFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-04",
      projectName: "SCN-04 Simple Cloud Network Allocation",
      scopeType: "cloud",
      artifactRequests: ["ip-allocation-table"],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    devices: [],
    racks: [],
    ports: [],
    links: [],
    segments: [
      {
        id: "segment-public-service",
        name: "public-service",
        segmentType: "service",
        cidr: "10.40.0.0/24",
        gateway: "10.40.0.1",
        purpose: "public-service",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "segment-internal-service",
        name: "internal-service",
        segmentType: "service",
        cidr: "10.41.0.0/24",
        gateway: "10.41.0.1",
        purpose: "internal-service",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-public-gateway",
        segmentId: "segment-public-service",
        allocationType: "gateway",
        ipAddress: "10.40.0.1",
        purpose: "public-gateway",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-public-api",
        segmentId: "segment-public-service",
        allocationType: "service",
        ipAddress: "10.40.0.10",
        hostname: "api-gateway",
        interfaceName: "eni-public",
        purpose: "public-api",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-internal-gateway",
        segmentId: "segment-internal-service",
        allocationType: "gateway",
        ipAddress: "10.41.0.1",
        purpose: "internal-gateway",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-internal-orders",
        segmentId: "segment-internal-service",
        allocationType: "service",
        ipAddress: "10.41.0.20",
        hostname: "orders-api",
        interfaceName: "eni-private",
        purpose: "orders-service",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn05DocumentAssistedDraftFixture() {
  return {
    requirement: {
      id: "req-scn-05",
      projectName: "SCN-05 Document Assisted Drafting",
      scopeType: "cloud" as const,
      artifactRequests: ["ip-allocation-table" as const],
      sourceRefs: [
        {
          kind: "user-input" as const,
          ref: "capture_solution_requirements",
          note: "Document-assisted drafting example",
        },
      ],
      statusConfidence: "confirmed" as const,
    },
    documentAssist: {
      documentSources: [
        {
          kind: "document" as const,
          ref: "fixtures/scn-05-supporting-design.pdf",
          note: "Supporting network design PDF",
        },
        {
          kind: "diagram" as const,
          ref: "fixtures/scn-05-topology-diagram.drawio",
          note: "Attached topology diagram",
        },
      ],
      candidateFacts: {
        racks: [],
        devices: [],
        links: [],
        segments: [
          {
            name: "Document Public Service",
            segmentType: "service" as const,
            cidr: "10.50.0.0/24",
            gateway: "10.50.0.1",
            purpose: "document-public-service",
            statusConfidence: "inferred" as const,
          },
        ],
        allocations: [
          {
            segmentName: "Document Public Service",
            allocationType: "service" as const,
            ipAddress: "10.50.0.10",
            hostname: "document-api",
            interfaceName: "eni-document",
            purpose: "document-api",
            statusConfidence: "unresolved" as const,
          },
        ],
      },
    },
  }
}

export function createScn05DocumentExtractionInputFixture() {
  const draftFixture = createScn05DocumentAssistedDraftFixture()

  return {
    requirement: draftFixture.requirement,
    documentAssist: {
      documentSources: draftFixture.documentAssist.documentSources,
      candidateFacts: {
        racks: [],
        devices: [],
        links: [],
        segments: [],
        allocations: [],
      },
    },
  }
}

export function createScn05ExtractedCandidateFactsFixture(documentSources?: Array<{
  kind: "document" | "diagram" | "image"
  ref: string
  note?: string
}>) {
  const draftFixture = createScn05DocumentAssistedDraftFixture()
  const sourceRefs = documentSources ?? draftFixture.documentAssist.documentSources

  return {
    racks: [],
    devices: [],
    links: [],
    segments: draftFixture.documentAssist.candidateFacts.segments.map((segment) => ({
      ...segment,
      sourceRefs,
    })),
    allocations: draftFixture.documentAssist.candidateFacts.allocations.map((allocation) => ({
      ...allocation,
      sourceRefs,
    })),
  }
}

export function createScn05PromotedDocumentAssistFixture() {
  return {
    ...createScn05DocumentAssistedDraftFixture(),
    confirmation: {
      entityRefs: [
        "segment:segment-document-public-service",
        "allocation:allocation-document-public-service-10-50-0-10",
      ],
    },
  }
}

export function createScn06MultiDocumentConflictFixture() {
  return {
    requirement: {
      id: "req-scn-06",
      projectName: "SCN-06 Multi Document Evidence Reconciliation",
      scopeType: "data-center" as const,
      artifactRequests: [
        "device-cabling-table" as const,
        "device-port-plan" as const,
        "ip-allocation-table" as const,
      ],
      sourceRefs: [],
      statusConfidence: "confirmed" as const,
    },
    devices: [
      {
        id: "sw1",
        name: "sw1",
        role: "core",
        rackId: "rack1",
        rackPosition: 10,
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "diagram" as const, ref: "topology.pdf", note: "Network topology diagram" }],
      },
      {
        id: "sw1-2",
        name: "sw1",
        role: "access",
        rackId: "rack2",
        rackPosition: 20,
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "inventory.csv", note: "Device inventory list" }],
      },
    ],
    racks: [
      {
        id: "rack1",
        name: "rack1",
        uHeight: 42,
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "diagram" as const, ref: "topology.pdf", note: "Network topology diagram" }],
      },
      {
        id: "rack2",
        name: "rack2",
        uHeight: 48,
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "inventory.csv", note: "Device inventory list" }],
      },
    ],
    ports: [
      {
        id: "sw1-port-1",
        deviceId: "sw1",
        name: "eth1/1",
        purpose: "uplink",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "diagram" as const, ref: "topology.pdf", note: "Network topology diagram" }],
      },
      {
        id: "sw1-port-1-2",
        deviceId: "sw1-2",
        name: "eth1/1",
        purpose: "server",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "port-config.xlsx", note: "Port configuration spreadsheet" }],
      },
    ],
    links: [
      {
        id: "link-sw1-server1",
        endpointA: { portId: "sw1-port-1" },
        endpointB: { portId: "server1-port-1" },
        purpose: "server-uplink",
        redundancyGroup: "server1-primary",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "diagram" as const, ref: "topology.pdf", note: "Network topology diagram" }],
      },
      {
        id: "link-sw1-server1-2",
        endpointA: { portId: "sw1-port-1-2" },
        endpointB: { portId: "server1-port-2" },
        purpose: "primary-uplink",
        redundancyGroup: "server1-main",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "cabling-diagram.dwg", note: "Cabling diagram" }],
      },
    ],
    segments: [
      {
        id: "mgmt-vlan",
        name: "management",
        segmentType: "vlan" as const,
        cidr: "192.168.10.0/24",
        gateway: "192.168.10.1",
        purpose: "device management",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "ip-plan.xlsx", note: "IP address planning spreadsheet" }],
      },
      {
        id: "mgmt-subnet",
        name: "management-backup",
        segmentType: "subnet" as const,
        cidr: "192.168.10.0/25",
        gateway: "192.168.10.1",
        purpose: "backup management",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "network-design.docx", note: "Network design document" }],
      },
    ],
    allocations: [
      {
        id: "alloc-sw1-mgmt",
        segmentId: "mgmt-vlan",
        allocationType: "device" as const,
        ipAddress: "192.168.10.10",
        deviceId: "sw1",
        hostname: "sw1-core",
        interfaceName: "mgmt0",
        purpose: "switch management",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "ip-plan.xlsx", note: "IP address planning spreadsheet" }],
      },
      {
        id: "alloc-sw1-backup",
        segmentId: "mgmt-subnet",
        allocationType: "device" as const,
        ipAddress: "192.168.10.10",
        deviceId: "sw1-2",
        hostname: "sw1-access",
        interfaceName: "eth0",
        purpose: "backup management",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "backup-ip-list.txt", note: "Backup IP allocation list" }],
      },
      {
        id: "alloc-server1-mgmt",
        segmentId: "mgmt-vlan",
        allocationType: "device" as const,
        ipAddress: "192.168.10.10",
        deviceId: "server1",
        hostname: "server1-app",
        interfaceName: "eth0",
        purpose: "server management",
        statusConfidence: "inferred" as const,
        sourceRefs: [{ kind: "document" as const, ref: "server-inventory.csv", note: "Server inventory list" }],
      },
    ],
  }
}
