import type { CloudSolutionSliceInput } from "../domain"

export function createScn01SingleRackConnectivityFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-01",
      projectName: "SCN-01 Single Rack Basic Connectivity",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-plan",
        "device-port-connection-table",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-switch-a",
        name: "switch-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-server-a",
        name: "server-a",
        role: "server",
        rackId: "rack-a",
        rackPosition: 10,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-server-b",
        name: "server-b",
        role: "server",
        rackId: "rack-a",
        rackPosition: 14,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-switch-a-1",
        deviceId: "device-switch-a",
        name: "eth0",
        purpose: "server-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-switch-a-2",
        deviceId: "device-switch-a",
        name: "eth1",
        purpose: "server-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-server-a-1",
        deviceId: "device-server-a",
        name: "eth0",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-server-b-1",
        deviceId: "device-server-b",
        name: "eth0",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-server-a",
        endpointA: { portId: "port-switch-a-1" },
        endpointB: { portId: "port-server-a-1" },
        purpose: "server-a-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-server-b",
        endpointA: { portId: "port-switch-a-2" },
        endpointB: { portId: "port-server-b-1" },
        purpose: "server-b-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-management",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.10.0.0/24",
        gateway: "10.10.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-gateway",
        segmentId: "segment-management",
        allocationType: "gateway",
        ipAddress: "10.10.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-server-a",
        segmentId: "segment-management",
        allocationType: "device",
        ipAddress: "10.10.0.10",
        deviceId: "device-server-a",
        interfaceName: "eth0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-server-b",
        segmentId: "segment-management",
        allocationType: "device",
        ipAddress: "10.10.0.11",
        deviceId: "device-server-b",
        interfaceName: "eth0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn02DualTorFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-02",
      projectName: "SCN-02 Dual ToR Redundant Rack",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-plan",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-tor-a",
        name: "tor-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-tor-b",
        name: "tor-b",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 2,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-storage-a",
        name: "storage-a",
        role: "storage",
        redundancyIntent: "dual-homed-required",
        rackId: "rack-a",
        rackPosition: 10,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-a",
        name: "compute-a",
        role: "server",
        redundancyIntent: "dual-homed-required",
        rackId: "rack-a",
        rackPosition: 14,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-tor-a-1",
        deviceId: "device-tor-a",
        name: "eth0",
        purpose: "uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-b-1",
        deviceId: "device-tor-b",
        name: "eth0",
        purpose: "uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-a-2",
        deviceId: "device-tor-a",
        name: "eth1",
        purpose: "uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-tor-b-2",
        deviceId: "device-tor-b",
        name: "eth1",
        purpose: "uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-storage-a-1",
        deviceId: "device-storage-a",
        name: "eth0",
        purpose: "storage-a-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-storage-a-2",
        deviceId: "device-storage-a",
        name: "eth1",
        purpose: "storage-a-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-1",
        deviceId: "device-compute-a",
        name: "eth0",
        purpose: "compute-a-uplink-a",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-2",
        deviceId: "device-compute-a",
        name: "eth1",
        purpose: "compute-a-uplink-b",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-storage-a-primary",
        endpointA: { portId: "port-tor-a-1" },
        endpointB: { portId: "port-storage-a-1" },
        purpose: "storage-primary",
        redundancyGroup: "storage-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-storage-a-secondary",
        endpointA: { portId: "port-tor-b-1" },
        endpointB: { portId: "port-storage-a-2" },
        purpose: "storage-secondary",
        redundancyGroup: "storage-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a-primary",
        endpointA: { portId: "port-tor-a-2" },
        endpointB: { portId: "port-compute-a-1" },
        purpose: "compute-primary",
        redundancyGroup: "compute-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a-secondary",
        endpointA: { portId: "port-tor-b-2" },
        endpointB: { portId: "port-compute-a-2" },
        purpose: "compute-secondary",
        redundancyGroup: "compute-a-dual-home",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-mgmt",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.20.0.0/24",
        gateway: "10.20.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "segment-storage",
        name: "storage",
        segmentType: "storage",
        cidr: "172.16.0.0/24",
        gateway: "172.16.0.1",
        purpose: "storage",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-mgmt-gateway",
        segmentId: "segment-mgmt",
        allocationType: "gateway",
        ipAddress: "10.20.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-gateway",
        segmentId: "segment-storage",
        allocationType: "gateway",
        ipAddress: "172.16.0.1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.20.0.10",
        deviceId: "device-storage-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-storage-a-service",
        segmentId: "segment-storage",
        allocationType: "device",
        ipAddress: "172.16.0.10",
        deviceId: "device-storage-a",
        interfaceName: "eth0/eth1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.20.0.11",
        deviceId: "device-compute-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-a-service",
        segmentId: "segment-storage",
        allocationType: "device",
        ipAddress: "172.16.0.11",
        deviceId: "device-compute-a",
        interfaceName: "eth0/eth1",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}

export function createScn03MultiRackPodFixture(): CloudSolutionSliceInput {
  return {
    requirement: {
      id: "req-scn-03",
      projectName: "SCN-03 Small Multi-Rack Pod",
      scopeType: "data-center",
      artifactRequests: [
        "device-cabling-table",
        "device-port-connection-table",
        "ip-allocation-table",
      ],
      sourceRefs: [],
      statusConfidence: "confirmed",
    },
    racks: [
      {
        id: "rack-a",
        name: "rack-a",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "rack-b",
        name: "rack-b",
        uHeight: 42,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    devices: [
      {
        id: "device-leaf-a",
        name: "leaf-a",
        role: "switch",
        rackId: "rack-a",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-leaf-b",
        name: "leaf-b",
        role: "switch",
        rackId: "rack-b",
        rackPosition: 1,
        rackUnitHeight: 1,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-a",
        name: "compute-a",
        role: "server",
        rackId: "rack-a",
        rackPosition: 12,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "device-compute-b",
        name: "compute-b",
        role: "server",
        rackId: "rack-b",
        rackPosition: 12,
        rackUnitHeight: 2,
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    ports: [
      {
        id: "port-leaf-a-1",
        deviceId: "device-leaf-a",
        name: "eth0",
        purpose: "inter-rack",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-b-1",
        deviceId: "device-leaf-b",
        name: "eth0",
        purpose: "inter-rack",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-a-2",
        deviceId: "device-leaf-a",
        name: "eth1",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-leaf-b-2",
        deviceId: "device-leaf-b",
        name: "eth1",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-a-1",
        deviceId: "device-compute-a",
        name: "eth0",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "port-compute-b-1",
        deviceId: "device-compute-b",
        name: "eth0",
        purpose: "compute-uplink",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    links: [
      {
        id: "link-inter-rack",
        endpointA: { portId: "port-leaf-a-1" },
        endpointB: { portId: "port-leaf-b-1" },
        purpose: "inter-rack-fabric",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-a",
        endpointA: { portId: "port-leaf-a-2" },
        endpointB: { portId: "port-compute-a-1" },
        purpose: "compute-access",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "link-compute-b",
        endpointA: { portId: "port-leaf-b-2" },
        endpointB: { portId: "port-compute-b-1" },
        purpose: "compute-access",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    segments: [
      {
        id: "segment-mgmt",
        name: "management",
        segmentType: "mgmt",
        cidr: "10.30.0.0/24",
        gateway: "10.30.0.1",
        purpose: "management",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "segment-service",
        name: "service",
        segmentType: "service",
        cidr: "10.31.0.0/24",
        gateway: "10.31.0.1",
        purpose: "service",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
    allocations: [
      {
        id: "allocation-compute-a-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.30.0.10",
        deviceId: "device-compute-a",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-compute-b-mgmt",
        segmentId: "segment-mgmt",
        allocationType: "device",
        ipAddress: "10.30.0.11",
        deviceId: "device-compute-b",
        interfaceName: "mgmt0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-leaf-a-service",
        segmentId: "segment-service",
        allocationType: "device",
        ipAddress: "10.31.0.10",
        deviceId: "device-leaf-a",
        interfaceName: "loopback0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
      {
        id: "allocation-leaf-b-service",
        segmentId: "segment-service",
        allocationType: "device",
        ipAddress: "10.31.0.11",
        deviceId: "device-leaf-b",
        interfaceName: "loopback0",
        sourceRefs: [],
        statusConfidence: "confirmed",
      },
    ],
  }
}
