import { z } from "zod"

import {
  PlanningDraftAgentBriefSchema,
  runDeviceCablingPlannerInChildSession,
} from "../../agents"
import type { WorkerInput, WorkerResult, WorkerRuntimeContext } from "../../coordinator/types"
import { finalizePlanningDraftStructuredInput } from "../planning-draft-shared"

const PlanningDraftWorkerContextSchema = z.object({
  plannerBrief: PlanningDraftAgentBriefSchema,
})

export async function executeDeviceCablingPlannerWorker(
  input: WorkerInput,
  runtime: WorkerRuntimeContext,
): Promise<WorkerResult> {
  const parsedContext = PlanningDraftWorkerContextSchema.safeParse(input.context ?? {})
  if (!parsedContext.success) {
    return {
      workerId: "device-cabling-planner",
      status: "failed",
      output: {},
      recommendations: [],
      errors: ["Device cabling planner worker requires context.plannerBrief."],
    }
  }

  const result = await runDeviceCablingPlannerInChildSession({
    brief: parsedContext.data.plannerBrief,
    runtime,
  })
  if (!result.success) {
    return result.result
  }

  return {
    workerId: "device-cabling-planner",
    status: result.result.status,
    output: {
      structuredInput: finalizePlanningDraftStructuredInput({
        structuredInput: result.result.output.structuredInput,
        plannerRef: "planner:device-cabling",
        plannerNote: "Advisory draft generated by the device cabling planner.",
      }),
      planningWarnings: result.result.output.planningWarnings,
    },
    recommendations: ["draft_topology_model"],
    ...(result.result.errors && result.result.errors.length > 0
      ? {
          errors: result.result.errors,
        }
      : {}),
  }
}

export default executeDeviceCablingPlannerWorker
